PR: Layouts and Reusable components
atlp-rwanda/rca-barefoot-team4-fe pull request #5
Opened 2023-04-19 17:32 UTC by divinirakiza

What does this PR do?
This PR contains code for the basic layouts of the projects, and reusable components. 

Description of the task to be completed?
The tasks involves making a scalable layout to render pages as children and reuse the available components.

How should this be manually tested?
- Run the codebase as a Next application
- Navigate to https://localhost:3000

2023-04-19 17:58 UTC, iradukundairenee requested changes
![Screenshot from 2023-04-19 19-51-37](https://user-images.githubusercontent.com/62067881/233160239-8856a42e-1e40-4020-9d9e-13292bc351fa.png)

@divinirakiza  Good job but resolve those eslint issues

2023-04-19 21:43 UTC, divinirakiza commented
@iradukundairenee , that version was updated, please pull the branch and run the lint command again.

2023-04-20 03:12 UTC, iradukundairenee commented
> @iradukundairenee , that version was updated, please pull the branch and run the lint command again.

sure @divinirakiza

2023-04-21 11:48 UTC, iradukundairenee approved these changes

2023-04-21 11:50 UTC, merged