feat: setup react-query
atlp-rwanda/rca-barefoot-team4-fe pull request #6
Opened 2023-04-27 15:18 UTC by divinirakiza

What does this PR do?
This PR contains  a working setup for react-query, an asynchronous state management tool for Next.js

Description of the task to be completed?
The tasks involves successfully installing up the library, setting up the library for Next.js and testing a simple functionality from the library.

How should this be manually tested?
Run the codebase as a Next application
Navigate to https://localhost:3000/ and checkout the random user data. The data comes from react-query.

2023-04-27 19:03 UTC, aimee-annabelle approved these changes

2023-04-28 08:10 UTC, iradukundairenee requested changes

2023-04-28 08:10 UTC, iradukundairenee commented on src/services/api.service.ts
> +      `https://random-data-api.com/api/v2/users`
nice job @divinirakiza  but you can store the API URL in a .env file to keep it separate from the code and make it easier to change in the future.

2023-04-28 08:22 UTC, iradukundairenee approved these changes

2023-04-28 08:22 UTC, merged